#!/usr/bin/env python3
"""
GLB visualization web app for Pixal3D resolution/seed comparison results.

Changes in this version:
- Viewer only loads simplified geometry-only GLB files; raw mesh GLB is never loaded by the page.
- Default mode is multi-view image comparison; mesh mode is opt-in and imports Three.js lazily only when needed.
- Layout uses seed sections and equal-width pipeline cards; normal previews are shown as a wrapped grid so all views are visible without horizontal or vertical clipping.
- Viewer colors are generated by a camera-space normal shader at display time.
- Current page image mode transfers only raw normal high-resolution views once; local low-resolution thumbnails are generated in browser, and simplified normals are loaded only on double-click comparison.
- Cross-page preloading is disabled by default. The selected page is fully downloaded and decoded once, then scroll/hover uses local browser memory caches.
- Loading progress avoids percentages for compressed responses; it reports current-page decode queue completion and bytes instead of clamping wrong values.
- Multi-view crop hover is warmed by decoded image caches and drawn on a single requestAnimationFrame, reducing view-to-view stalls.
- Two scores are persisted to a CSV table through Flask APIs: overall and local. New rows default to 2/2 and summaries are grouped by resolution.
- Wireframe geometry is prebuilt once immediately after each simplified GLB loads; the UI slider only changes material linewidth/visibility.
- /files route serves gzip-compressed cached assets when the browser supports it.

Expected manifest fields from run_pixal3d_resolution_grid_geometry.py:
  raw_mesh_glb, simplified_mesh_glb, normal_raw, normal_simplified, raw_stats, simplified_stats
Legacy fallback fields are also handled where possible.
"""

import argparse
import csv
import gzip
import hashlib
import json
import mimetypes
import os
import shutil
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from flask import Flask, Response, abort, jsonify, render_template_string, request, send_file, send_from_directory


HTML = r"""
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Pixal3D GLB 分辨率对比</title>
  <style>
    :root {
      --bg: #0f1115;
      --panel: #171a21;
      --panel2: #202634;
      --text: #edf0f7;
      --muted: #9aa4b2;
      --border: #2b3342;
      --accent: #8ab4ff;
      --danger: #ff8a8a;
      --ok: #9cffb2;
      --viewer-height: 320px;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }
    header {
      position: sticky;
      top: 0;
      z-index: 100;
      background: rgba(15, 17, 21, 0.94);
      backdrop-filter: blur(10px);
      border-bottom: 1px solid var(--border);
      padding: 10px 14px;
    }
    .topbar {
      display: flex;
      flex-wrap: wrap;
      align-items: end;
      gap: 10px;
    }
    h1 {
      margin: 0 10px 0 0;
      font-size: 17px;
      white-space: nowrap;
      line-height: 32px;
    }
    .control {
      display: grid;
      gap: 4px;
      min-width: 150px;
    }
    label { color: var(--muted); font-size: 12px; }
    select, button {
      color: var(--text);
      background: var(--panel2);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 7px 10px;
      cursor: pointer;
      height: 34px;
    }
    button.active { border-color: var(--accent); color: var(--accent); }
    .wire-control {
      display: grid;
      gap: 4px;
      background: var(--panel2);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 6px 10px;
    }
    .wire-control .wire-label-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 8px;
      font-size: 12px;
      color: var(--muted);
    }
    .wire-control output { color: var(--text); font-variant-numeric: tabular-nums; }
    .wire-control input[type=range] {
      width: 100%;
      accent-color: var(--accent);
      cursor: pointer;
    }
    .wrap { padding: 14px; }
    .intro {
      display: grid;
      grid-template-columns: 118px minmax(0, 1fr);
      gap: 14px;
      align-items: center;
      margin-bottom: 12px;
      background: linear-gradient(180deg, #171a21, #141821);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 12px;
    }
    .intro img {
      width: 106px;
      height: 106px;
      object-fit: contain;
      background: #000;
      border: 1px solid var(--border);
      border-radius: 10px;
      cursor: zoom-in;
    }
    .intro-main { min-width: 0; }
    .intro h2 { margin: 0 0 8px 0; font-size: 16px; }
    .intro p { margin: 6px 0 0 0; color: var(--muted); font-size: 13px; }
    .badge-row { display: flex; flex-wrap: wrap; gap: 6px; }
    .badge {
      display: inline-flex;
      align-items: center;
      min-height: 24px;
      padding: 3px 8px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: #10141c;
      color: var(--muted);
      font-size: 12px;
      white-space: nowrap;
    }
    .status-line { color: var(--ok); font-size: 12px; margin-top: 6px; }
    .score-summary {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
      margin-top: 8px;
      font-size: 12px;
      color: var(--muted);
    }
    .score-chip {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      min-height: 24px;
      padding: 3px 8px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: #0e131b;
      color: var(--muted);
      white-space: nowrap;
    }
    .score-chip strong { color: var(--text); font-weight: 650; }
    .grid-scroll {
      overflow-x: auto;
      overflow-y: visible;
      border: 1px solid var(--border);
      border-radius: 14px;
      background: #121620;
    }
    .comparison-root {
      display: grid;
      gap: 14px;
      min-width: 100%;
      padding: 12px;
    }
    .seed-section {
      display: grid;
      gap: 10px;
      min-width: 100%;
      background: #151922;
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 10px;
    }
    .seed-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 10px;
      padding: 2px 2px 0 2px;
      color: var(--muted);
      font-size: 12px;
    }
    .seed-header strong {
      color: var(--text);
      font-size: 14px;
    }
    .pipeline-grid {
      display: grid;
      gap: 10px;
      align-items: stretch;
    }
    .result-card {
      display: grid;
      grid-template-rows: auto auto auto auto;
      gap: 8px;
      min-width: 0;
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 9px;
      text-align: center;
    }
    .card-missing {
      min-height: calc(var(--viewer-height) + 132px);
      display: grid;
      place-items: center;
      color: var(--danger);
      background: #140f12;
      border: 1px dashed var(--danger);
      border-radius: 12px;
      font-size: 13px;
      text-align: center;
      padding: 18px;
    }
    table {
      border-collapse: separate;
      border-spacing: 0;
      table-layout: fixed;
      width: 100%;
      min-width: 0;
      background: var(--panel);
    }
    col.seed-col { width: 72px; }
    th, td {
      border-right: 1px solid var(--border);
      border-bottom: 1px solid var(--border);
      padding: 9px;
      vertical-align: top;
      text-align: center;
      word-break: break-word;
    }
    th {
      position: sticky;
      top: 0;
      z-index: 20;
      background: #151922;
      text-align: center;
      font-size: 14px;
      font-weight: 700;
    }
    th:first-child, td:first-child {
      position: sticky;
      left: 0;
      z-index: 25;
      background: #151922;
      width: 72px;
      min-width: 72px;
      text-align: center;
      font-weight: 700;
      vertical-align: middle;
    }
    th:first-child { z-index: 30; }
    .cell {
      display: grid;
      gap: 8px;
      min-width: 0;
      justify-items: stretch;
      text-align: center;
    }
    .cell-title {
      display: grid;
      grid-template-columns: 1fr;
      justify-items: center;
      gap: 2px;
      color: var(--muted);
      font-size: 12px;
      line-height: 1.25;
      min-height: 34px;
    }
    .cell-title strong { color: var(--text); font-size: 13px; font-weight: 650; }
    .viewer {
      width: 100%;
      height: var(--viewer-height);
      min-height: 220px;
      background: #06080c;
      border: 1px solid var(--border);
      border-radius: 10px;
      overflow: hidden;
      position: relative;
    }
    .viewer canvas { display: block; width: 100%; height: 100%; }
    .viewer .loading {
      position: absolute;
      inset: 0;
      display: grid;
      place-items: center;
      color: var(--muted);
      font-size: 13px;
      pointer-events: none;
      text-align: center;
      padding: 16px;
    }
    .viewer-slot {
      width: 100%;
      height: var(--viewer-height);
      min-height: 220px;
      background: #06080c;
      border: 1px solid var(--border);
      border-radius: 10px;
      overflow: hidden;
      position: relative;
    }
    .viewer-slot .viewer {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      min-height: 0;
      border: 0;
      border-radius: 0;
    }
    .viewer-slot.image-mode .viewer { visibility: hidden; pointer-events: none; }
    .zoom-viewer {
      position: absolute;
      inset: 0;
      display: none;
      background: #000;
      overflow: hidden;
    }
    .viewer-slot.image-mode .zoom-viewer { display: block; }
    .zoom-viewer canvas {
      display: block;
      width: 100%;
      height: 100%;
      background: #000;
    }
    .zoom-empty {
      position: absolute;
      inset: 0;
      display: grid;
      place-items: center;
      text-align: center;
      color: var(--muted);
      font-size: 13px;
      padding: 18px;
      background: #07090d;
    }
    .zoom-viewer.has-image .zoom-empty { display: none; }
    .zoom-caption {
      position: absolute;
      left: 10px;
      bottom: 10px;
      max-width: calc(100% - 126px);
      padding: 5px 7px;
      border-radius: 7px;
      background: rgba(0, 0, 0, 0.72);
      color: #fff;
      font-size: 11px;
      line-height: 1.25;
      text-align: left;
      pointer-events: none;
    }
    .zoom-exit {
      position: absolute;
      right: 10px;
      bottom: 10px;
      height: 28px;
      padding: 4px 8px;
      font-size: 12px;
      background: rgba(32, 38, 52, 0.88);
    }
    .links {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      gap: 8px;
      font-size: 12px;
      align-items: center;
      min-height: 20px;
    }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    .small { color: var(--muted); font-size: 12px; }
    .missing {
      height: var(--viewer-height);
      display: grid;
      place-items: center;
      color: var(--danger);
      background: #140f12;
      border: 1px dashed var(--danger);
      border-radius: 10px;
      font-size: 13px;
      text-align: center;
      padding: 18px;
    }
    .view-panel {
      display: grid;
      gap: 8px;
      min-width: 0;
      overflow: visible;
      background: #10141c;
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 8px;
    }
    .view-panel-head {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 8px;
      color: var(--muted);
      font-size: 12px;
      line-height: 1.2;
    }
    .view-buttons {
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      grid-auto-rows: auto;
      gap: 7px;
      overflow: visible;
      padding: 0;
      align-items: start;
    }
    .view-button {
      /* Important: global `button { height: 34px; }` is only for toolbar buttons.
         Normal-view thumbnails are also <button>, so explicitly release that fixed height;
         otherwise the image is clipped to a thin strip, which is the incomplete display in the screenshot. */
      height: auto;
      min-height: 0;
      min-width: 0;
      line-height: normal;
      position: relative;
      border: 1px solid var(--border);
      background: #0b0d12;
      border-radius: 8px;
      padding: 4px;
      cursor: zoom-in;
      display: grid;
      grid-template-rows: auto auto;
      align-content: start;
      gap: 3px;
      overflow: hidden;
    }
    .view-button:hover { border-color: var(--accent); }
    .thumb-frame {
      position: relative;
      width: 100%;
      aspect-ratio: 1 / 1;
      display: block;
      overflow: hidden;
      border-radius: 5px;
      background: #000;
    }
    .view-button img {
      width: 100%;
      height: 100%;
      object-fit: contain;
      background: #000;
      display: block;
      opacity: 0;
      transition: opacity 120ms linear;
    }
    .view-button img.ready { opacity: 1; }
    .thumb-placeholder {
      position: absolute;
      inset: 0;
      display: grid;
      place-items: center;
      color: var(--muted);
      font-size: 10px;
      background: #000;
      pointer-events: none;
    }
    .thumb-frame.ready .thumb-placeholder { display: none; }
    .view-button .view-label {
      color: var(--muted);
      font-size: 10px;
      line-height: 1.1;
      text-align: center;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .face-badge {
      position: absolute;
      left: 4px;
      top: 4px;
      padding: 2px 5px;
      border-radius: 5px;
      background: rgba(0, 0, 0, 0.72);
      color: #fff;
      font-size: 10px;
      line-height: 1.1;
      pointer-events: none;
    }
    .roi-box {
      position: absolute;
      display: none;
      border: 2px solid #ffffff;
      outline: 1px solid rgba(0,0,0,0.72);
      box-shadow: 0 0 0 999px rgba(0,0,0,0.20);
      pointer-events: none;
    }
    .view-button.roi-active { border-color: var(--accent); }
    .view-button.roi-active .roi-box { display: block; }
    .score-panel {
      display: grid;
      gap: 6px;
      padding: 7px;
      border: 1px solid var(--border);
      border-radius: 10px;
      background: #10141c;
      text-align: left;
    }
    .score-title-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 8px;
      color: var(--muted);
      font-size: 11px;
      line-height: 1.2;
    }
    .score-title-row strong { color: var(--text); font-size: 12px; }
    .score-row {
      display: grid;
      grid-template-columns: 44px repeat(3, minmax(0, 1fr));
      gap: 5px;
      align-items: center;
    }
    .score-row-label {
      color: var(--muted);
      font-size: 11px;
      white-space: nowrap;
    }
    .score-btn {
      height: 26px;
      padding: 3px 0;
      font-size: 12px;
      border-radius: 6px;
      background: #151a24;
    }
    .score-btn.active {
      border-color: var(--accent);
      color: var(--accent);
      background: #142036;
    }
    .score-btn.saving { opacity: 0.55; pointer-events: none; }
    .score-avg {
      color: var(--muted);
      font-size: 11px;
      font-variant-numeric: tabular-nums;
    }
    @media (max-width: 1450px) {
      .view-buttons { grid-template-columns: repeat(4, minmax(0, 1fr)); }
    }
    @media (max-width: 900px) {
      .view-buttons { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    }
    body.modal-open { overflow: hidden; }
    .modal-backdrop {
      position: fixed;
      inset: 0;
      z-index: 1000;
      background: rgba(0, 0, 0, 0.68);
      backdrop-filter: blur(9px);
      display: none;
      align-items: center;
      justify-content: center;
      padding: 30px;
    }
    .modal-backdrop.visible { display: flex; }
    .modal {
      width: min(1500px, 96vw);
      max-height: 94vh;
      overflow: auto;
      background: #11151d;
      border: 1px solid var(--border);
      border-radius: 16px;
      box-shadow: 0 24px 100px rgba(0,0,0,0.6);
      padding: 14px;
    }
    .modal.single { width: min(1100px, 94vw); }
    .modal-head {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 12px;
      margin-bottom: 10px;
    }
    .modal-title { font-weight: 700; font-size: 15px; }
    .modal-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .modal-grid.single { grid-template-columns: 1fr; }
    .modal-card {
      background: #07090d;
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 10px;
    }
    .modal-card h3 { margin: 0 0 8px 0; font-size: 14px; color: var(--muted); }
    .modal-card img {
      width: 100%;
      max-height: 78vh;
      object-fit: contain;
      background: #000;
      border-radius: 8px;
    }
    @media (max-width: 1200px) {
      .intro { grid-template-columns: 1fr; }
      .modal-grid { grid-template-columns: 1fr; }
    }
    @media (max-width: 780px) {
      .control, .wire-control, select, button { width: 100%; }
      h1 { width: 100%; }
    }
  </style>
</head>
<body>
  <header>
    <div class="topbar">
      <h1>Pixal3D GLB 对比</h1>
      <div class="control">
        <label for="imageSelect">输入图片</label>
        <select id="imageSelect"></select>
      </div>
      <div class="control">
        <label for="pipelineSelect">显示精度 / pipeline</label>
        <select id="pipelineSelect"><option value="__all__">全部</option></select>
      </div>
      <div class="wire-control">
        <div class="wire-label-row"><label for="wireWidthRange">黑色网格粗细</label><output id="wireWidthValue">关</output></div>
        <input id="wireWidthRange" type="range" min="0" max="6" step="0.25" value="0" />
      </div>
      <div class="wire-control zoom-control">
        <div class="wire-label-row"><label for="zoomWindowRange">法向图细节框范围</label><output id="zoomWindowValue">28%</output></div>
        <input id="zoomWindowRange" type="range" min="8" max="80" step="1" value="28" />
      </div>
      <button id="toggleViewButtons">多视角图：关</button>
      <button id="resetCamera">重置视角</button>
      <button id="exportScores">导出评分表格</button>
      <div class="control">
        <label for="heightSelect">窗口高度</label>
        <select id="heightSelect">
          <option value="260px">260</option>
          <option value="320px" selected>320</option>
          <option value="420px">420</option>
          <option value="560px">560</option>
        </select>
      </div>
    </div>
  </header>

  <div class="wrap">
    <section class="intro">
      <img id="inputImage" title="点击放大原图" />
      <div class="intro-main">
        <h2 id="imageTitle">输入图片</h2>
        <div class="badge-row">
          <span class="badge">同步旋转 / 缩放 / 平移</span>
          <span class="badge">默认多视角法向图模式</span>
          <span class="badge">多视图默认不加载 Three.js / GLB</span>
          <span class="badge">当前页图片一次性完整解码</span>
        </div>
        <p id="imageMeta"></p>
        <div class="score-summary" id="scoreSummary">评分统计加载中...</div>
        <p class="status-line" id="preloadStatus"></p>
      </div>
    </section>
    <section class="grid-scroll" id="gridRoot"></section>
  </div>

  <div class="modal-backdrop" id="imageModal">
    <div class="modal" id="modalBox">
      <div class="modal-head">
        <div class="modal-title" id="modalTitle">图片预览</div>
        <button id="closeModal">× 关闭</button>
      </div>
      <div class="modal-grid" id="modalGrid">
        <div class="modal-card" id="modalRawCard">
          <h3 id="modalRawLabel">raw mesh normal</h3>
          <img id="modalRaw" />
        </div>
        <div class="modal-card" id="modalSimpleCard">
          <h3 id="modalSimpleLabel">simplified mesh normal</h3>
          <img id="modalSimple" />
        </div>
      </div>
    </div>
  </div>

<script type="importmap">
{
  "imports": {
    "three": "https://unpkg.com/three@0.160.0/build/three.module.js",
    "three/addons/": "https://unpkg.com/three@0.160.0/examples/jsm/"
  }
}
</script>
<script type="module">
// Three.js is intentionally loaded lazily. In the default multi-view image mode,
// importing and parsing Three.js/GLTFLoader is pure overhead and can make page open feel stuck.
let THREE = null;
let OrbitControls = null;
let GLTFLoader = null;
let LineSegments2 = null;
let LineSegmentsGeometry = null;
let LineMaterial = null;
let gltfLoader = null;
let threeImportPromise = null;
async function ensureThree() {
  if (THREE && gltfLoader) return;
  if (!threeImportPromise) {
    threeImportPromise = Promise.all([
      import("three"),
      import("three/addons/controls/OrbitControls.js"),
      import("three/addons/loaders/GLTFLoader.js"),
      import("three/addons/lines/LineSegments2.js"),
      import("three/addons/lines/LineSegmentsGeometry.js"),
      import("three/addons/lines/LineMaterial.js"),
    ]).then(([threeModule, controlsModule, loaderModule, line2Module, lineGeoModule, lineMatModule]) => {
      THREE = threeModule;
      OrbitControls = controlsModule.OrbitControls;
      GLTFLoader = loaderModule.GLTFLoader;
      LineSegments2 = line2Module.LineSegments2;
      LineSegmentsGeometry = lineGeoModule.LineSegmentsGeometry;
      LineMaterial = lineMatModule.LineMaterial;
      gltfLoader = new GLTFLoader();
    });
  }
  await threeImportPromise;
}

const MANIFEST = {{ manifest_json | safe }};
const FILE_PREFIX = "/files/";
const PREFETCH_PAGES = {{ prefetch_pages_json | safe }};
const PREFETCH_MESHES = {{ prefetch_meshes_json | safe }};
const SERVER_COMPRESSION = {{ server_compression_json | safe }};
const SCORE_TABLE_PATH = {{ score_table_path_json | safe }};

let selectedImageIndex = 0;
let visiblePipelineFilter = "__all__";
let wireframeLineWidth = 0;
let wireframeUpdateRequested = false;
let multiViewMode = true;
let suppressSync = false;
let frameRequested = false;
let viewerObserver = null;
let preloadGeneration = 0;
let zoomWindowFraction = 0.28;
let zoomUpdateRequested = false;
let zoomDrawToken = 0;
let zoomState = {
  active: false,
  seed: null,
  viewIdx: null,
  centerX: 0.5,
  centerY: 0.5,
  sourceTitle: "",
};
const viewers = [];
const previewImageCache = new Map();       // raw normal url -> Promise<HTMLImageElement>, resolved only after decode()
const thumbnailUrlCache = new Map();       // raw normal url -> local object URL for a downsampled thumbnail
const thumbnailPromiseCache = new Map();   // raw normal url -> Promise<objectURL>
const imageCacheUrls = new Set();          // URLs known to be image decodes; cleared on page/mode switch to limit memory
const THUMB_MAX_SIZE = 160;                // thumbnails below are local low-res copies; zoom uses high-res raw normal
const meshBufferCache = new Map();         // url -> ArrayBuffer, populated by viewer loads only in mesh mode
const meshBufferPromises = new Map();      // url -> Promise<ArrayBuffer>, shares in-flight fetches
const assetState = new Map();              // url -> "queued" | "ready" | "failed"
const SCORE_FIELDS = [
  { key: "overall", label: "整体" },
  { key: "local", label: "局部" },
];
const DEFAULT_SCORE = 2;
let scoreRows = new Map();                 // `${image_id}||${seed}||${pipeline}` -> row
let scoreSummary = { by_resolution: {} };

function requestRender() {
  if (frameRequested) return;
  frameRequested = true;
  requestAnimationFrame(renderFrame);
}
function renderFrame() {
  frameRequested = false;
  for (const v of viewers) {
    if (v.disposed || !v.visible || !v.loaded) continue;
    const resized = v.resize();
    if (resized) v.dirty = true;
    if (!v.dirty) continue;
    v.renderer.render(v.scene, v.camera);
    v.dirty = false;
  }
}
function markAllDirty() {
  for (const v of viewers) v.dirty = true;
  requestRender();
}
function fileUrl(relPath) {
  if (!relPath) return "";
  return FILE_PREFIX + String(relPath).split("/").map(encodeURIComponent).join("/");
}
const KNOWN_PIPELINE_ORDER = [
  "512",
  "1024",
  "1024_cascade",
  "1536_cascade",
];
const KNOWN_PIPELINE_RANK = new Map(KNOWN_PIPELINE_ORDER.map((name, idx) => [name, idx]));

function getUnique(values) {
  return [...new Set(values.filter(v => v !== undefined && v !== null && String(v) !== ""))].sort((a, b) => {
    if (typeof a === "number" && typeof b === "number") return a - b;
    return String(a).localeCompare(String(b), undefined, { numeric: true, sensitivity: "base" });
  });
}
function getResultPipelineType(result) {
  if (!result) return "";
  return String(
    result.pipeline_type ??
    result.resolution_type ??
    result.resolution_name ??
    result.name ??
    result.resolution ??
    result.effective_resolution ??
    ""
  );
}
function comparePipelineTypes(a, b) {
  const sa = String(a);
  const sb = String(b);
  const ra = KNOWN_PIPELINE_RANK.has(sa) ? KNOWN_PIPELINE_RANK.get(sa) : Number.POSITIVE_INFINITY;
  const rb = KNOWN_PIPELINE_RANK.has(sb) ? KNOWN_PIPELINE_RANK.get(sb) : Number.POSITIVE_INFINITY;
  if (ra !== rb) return ra - rb;
  const na = Number((sa.match(/^\d+/) || [Number.POSITIVE_INFINITY])[0]);
  const nb = Number((sb.match(/^\d+/) || [Number.POSITIVE_INFINITY])[0]);
  if (na !== nb) return na - nb;
  return sa.localeCompare(sb, undefined, { numeric: true, sensitivity: "base" });
}
function getPipelineTypes(imageRecord) {
  // Important: use the union of top-level manifest.pipeline_types and actual per-result pipeline_type.
  // Older/incremental manifests can keep a stale top-level pipeline_types list, while new result rows
  // already contain 2048_* / 4096_* / custom labels. If we trust only manifest.pipeline_types,
  // those new resolutions are silently hidden in the UI.
  const values = [];
  for (const p of (MANIFEST.pipeline_types || [])) values.push(String(p));
  for (const r of (imageRecord.results || [])) {
    const p = getResultPipelineType(r);
    if (p) values.push(p);
  }
  return [...new Set(values)].sort(comparePipelineTypes);
}
function getSeeds(imageRecord) {
  return getUnique((imageRecord.results || []).map(r => r.seed));
}
function findResult(imageRecord, seed, pipelineType) {
  return (imageRecord.results || []).find(r => Number(r.seed) === Number(seed) && getResultPipelineType(r) === String(pipelineType));
}
function populatePipelineSelect(pipelineTypes) {
  const select = document.getElementById("pipelineSelect");
  if (!select) return;
  const previous = visiblePipelineFilter;
  select.innerHTML = `<option value="__all__">全部 (${pipelineTypes.length})</option>` +
    pipelineTypes.map(p => `<option value="${escapeHtml(p)}">${escapeHtml(p)}</option>`).join("");
  const valid = previous === "__all__" || pipelineTypes.includes(previous);
  visiblePipelineFilter = valid ? previous : "__all__";
  select.value = visiblePipelineFilter;
}
function normalViews(normalObj) {
  const views = normalObj && normalObj.views ? normalObj.views : [];
  if (views.length && typeof views[0] === "string") {
    return views.map((p, i) => ({ view_idx: i, path: p }));
  }
  return views || [];
}
function simplifiedMeshPath(r) {
  return r.simplified_mesh_glb || r.simplified_mesh || r.simplified_mesh_ply || r.simplified_mesh_glb_gz || "";
}
function rawMeshPath(r) {
  return r.raw_mesh_glb || r.raw_mesh || "";
}
function activeMeshPath(r) {
  // Critical: never return raw mesh here. Raw GLB can be millions of faces and can OOM the browser.
  return simplifiedMeshPath(r);
}
function disposeViewers() {
  for (const v of viewers) v.dispose();
  viewers.length = 0;
}
function populateImageSelect() {
  const select = document.getElementById("imageSelect");
  select.innerHTML = "";
  MANIFEST.images.forEach((img, idx) => {
    const option = document.createElement("option");
    option.value = idx;
    option.textContent = `${idx}: ${img.input_name || img.image_id}`;
    select.appendChild(option);
  });
  const params = new URLSearchParams(window.location.search);
  const wanted = params.get("image");
  if (wanted) {
    const idx = MANIFEST.images.findIndex(x => x.image_id === wanted || x.input_name === wanted);
    if (idx >= 0) selectedImageIndex = idx;
  }
  select.value = selectedImageIndex;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
function scoreKey(imageId, seed, pipelineType) {
  return `${imageId}||${seed}||${pipelineType}`;
}
function scoreResolution(result, pipelineType) {
  // Treat the visible pipeline label as the resolution setting, e.g. 1024 vs 1024_cascade.
  // This avoids merging plain 1024 and 1024_cascade when both have effective_resolution=1024.
  const value = pipelineType ?? getResultPipelineType(result) ?? (result && (result.resolution ?? result.effective_resolution ?? result.target_resolution ?? result.mesh_resolution));
  return String(value ?? "unknown");
}
function scoreValueFromRow(row, key) {
  const fallback = key === "overall" ? row.score_1 : row.score_2;
  const raw = row[`${key}_score`] ?? row[key] ?? fallback;
  const n = Number(raw);
  return Number.isFinite(n) && n >= 1 && n <= 3 ? n : DEFAULT_SCORE;
}
function normalizeScoreRow(row) {
  const scores = {
    overall: scoreValueFromRow(row, "overall"),
    local: scoreValueFromRow(row, "local"),
  };
  return {
    ...row,
    resolution: String(row.resolution || row.pipeline_type || "unknown"),
    scores,
  };
}
async function loadScores() {
  try {
    const res = await fetch("/api/scores", { cache: "no-store" });
    if (!res.ok) throw new Error(`score api ${res.status}`);
    const data = await res.json();
    scoreRows = new Map();
    for (const row of data.rows || []) {
      const norm = normalizeScoreRow(row);
      scoreRows.set(scoreKey(norm.image_id, norm.seed, norm.pipeline_type), norm);
    }
    scoreSummary = data.summary || { by_resolution: {} };
    renderScoreSummary();
  } catch (err) {
    console.error(err);
    const el = document.getElementById("scoreSummary");
    if (el) el.textContent = "评分表读取失败；检查 Flask 控制台。";
  }
}
function getScoreRow(imageId, seed, pipelineType, resolution="unknown") {
  return scoreRows.get(scoreKey(imageId, seed, pipelineType)) || {
    image_id: imageId,
    seed: String(seed),
    pipeline_type: pipelineType,
    resolution: String(resolution || pipelineType || "unknown"),
    scores: { overall: DEFAULT_SCORE, local: DEFAULT_SCORE },
  };
}
function scoreAverage(scores) {
  return (Number(scores.overall) + Number(scores.local)) / 2;
}
function buildScorePanel(imageRecord, seed, pipelineType, resolution) {
  const row = getScoreRow(imageRecord.image_id, seed, pipelineType, resolution);
  const avg = scoreAverage(row.scores);
  const rows = SCORE_FIELDS.map(field => {
    const current = row.scores[field.key];
    const buttons = [1, 2, 3].map(v => `<button class="score-btn ${current === v ? "active" : ""}" data-image-id="${escapeHtml(imageRecord.image_id)}" data-input-name="${escapeHtml(imageRecord.input_name || "")}" data-seed="${escapeHtml(seed)}" data-pipeline="${escapeHtml(pipelineType)}" data-resolution="${escapeHtml(resolution)}" data-score-key="${field.key}" data-score-value="${v}" title="${escapeHtml(field.label)} = ${v}">${v}</button>`).join("");
    return `<div class="score-row"><span class="score-row-label">${escapeHtml(field.label)}</span>${buttons}</div>`;
  }).join("");
  return `<div class="score-panel" data-image-id="${escapeHtml(imageRecord.image_id)}" data-seed="${escapeHtml(seed)}" data-pipeline="${escapeHtml(pipelineType)}" data-resolution="${escapeHtml(resolution)}">
    <div class="score-title-row"><strong>质量评分</strong><span class="score-avg">avg: ${avg.toFixed(2)}</span></div>
    ${rows}
  </div>`;
}
function renderScoreSummary() {
  const el = document.getElementById("scoreSummary");
  if (!el) return;
  const byResolution = scoreSummary.by_resolution || {};
  const names = Object.keys(byResolution).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  if (!names.length) {
    el.innerHTML = `<span class="score-chip">评分表：${escapeHtml(SCORE_TABLE_PATH)}，初始化后默认整体=2、局部=2</span>`;
    return;
  }
  el.innerHTML = `<span class="score-chip">评分表：${escapeHtml(SCORE_TABLE_PATH)}</span>` + names.map(name => {
    const s = byResolution[name];
    return `<span class="score-chip"><strong>${escapeHtml(name)}</strong> total ${s.total_avg === null ? "-" : Number(s.total_avg).toFixed(2)} · 整体 ${s.overall_avg === null ? "-" : Number(s.overall_avg).toFixed(2)} · 局部 ${s.local_avg === null ? "-" : Number(s.local_avg).toFixed(2)} · n=${s.count_rows || 0}</span>`;
  }).join("");
}
function refreshScorePanel(imageId, seed, pipelineType) {
  const panel = [...document.querySelectorAll(".score-panel")].find(el =>
    el.dataset.imageId === String(imageId) &&
    el.dataset.seed === String(seed) &&
    el.dataset.pipeline === String(pipelineType)
  );
  if (!panel) return;
  const row = getScoreRow(imageId, seed, pipelineType, panel.dataset.resolution || pipelineType);
  panel.querySelectorAll(".score-btn").forEach(btn => {
    const key = btn.dataset.scoreKey;
    const value = Number(btn.dataset.scoreValue);
    btn.classList.toggle("active", row.scores[key] === value);
    btn.classList.remove("saving");
  });
  const avg = scoreAverage(row.scores);
  const avgEl = panel.querySelector(".score-avg");
  if (avgEl) avgEl.textContent = `avg: ${avg.toFixed(2)}`;
}
async function saveScoreFromButton(btn) {
  const payload = {
    image_id: btn.dataset.imageId,
    input_name: btn.dataset.inputName || "",
    seed: btn.dataset.seed,
    pipeline_type: btn.dataset.pipeline,
    resolution: btn.dataset.resolution || btn.dataset.pipeline,
    score_key: btn.dataset.scoreKey,
    score_value: Number(btn.dataset.scoreValue),
  };
  btn.classList.add("saving");
  try {
    const res = await fetch("/api/score", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error(`score api ${res.status}`);
    const data = await res.json();
    const row = normalizeScoreRow(data.row);
    scoreRows.set(scoreKey(row.image_id, row.seed, row.pipeline_type), row);
    scoreSummary = data.summary || scoreSummary;
    refreshScorePanel(row.image_id, row.seed, row.pipeline_type);
    renderScoreSummary();
  } catch (err) {
    console.error(err);
    btn.classList.remove("saving");
    alert("评分写入失败：请看 Flask / 浏览器控制台。CSV 可能没有写权限。");
  }
}

function renderPage() {
  preloadGeneration += 1;
  disposeViewers();
  clearDecodedImageCaches();
  zoomState.active = false;
  updateModeToggleButton();
  const imageRecord = MANIFEST.images[selectedImageIndex];
  if (!imageRecord) {
    document.getElementById("gridRoot").innerHTML = `<div class="missing">manifest.json 里没有 image records</div>`;
    return;
  }
  const inputUrl = fileUrl(imageRecord.input_image);
  const inputImage = document.getElementById("inputImage");
  inputImage.src = inputUrl;
  inputImage.onclick = () => openSingleImage(`输入图片 · ${imageRecord.input_name || imageRecord.image_id}`, inputUrl);
  document.getElementById("imageTitle").textContent = imageRecord.input_name || imageRecord.image_id;
  document.getElementById("imageMeta").textContent = `${imageRecord.results.length} 条结果；${getPipelineTypes(imageRecord).length} 个可视化 pipeline；当前为 ${multiViewMode ? "多视图 raw normal 模式（默认；不加载 Three.js / GLB / simplified normal）" : "3D Mesh 模式"}；跨页面预加载关闭；当前页只完整下载 raw normal，高分辨率用于上方细节图，下方缩略图由本地降采样生成。`;

  const allPipelineTypes = getPipelineTypes(imageRecord);
  populatePipelineSelect(allPipelineTypes);
  const pipelineTypes = visiblePipelineFilter === "__all__"
    ? allPipelineTypes
    : allPipelineTypes.filter(p => p === visiblePipelineFilter);
  const seeds = getSeeds(imageRecord);
  const minCardWidth = pipelineTypes.length >= 4 ? 360 : 380;
  if (!pipelineTypes.length) {
    document.getElementById("gridRoot").innerHTML = `<div class="missing">当前图片没有可显示的 pipeline。请检查 manifest.json 中 images[].results[].pipeline_type。</div>`;
    return;
  }
  let cardSerial = 0;
  let html = `<div class="comparison-root">`;
  for (const seed of seeds) {
    html += `<section class="seed-section">
      <div class="seed-header"><strong>seed ${seed}</strong><span>${pipelineTypes.length} 个 pipeline 设置</span></div>
      <div class="pipeline-grid" style="grid-template-columns: repeat(${pipelineTypes.length}, minmax(${minCardWidth}px, 1fr));">`;
    for (const p of pipelineTypes) {
      const r = findResult(imageRecord, seed, p);
      if (!r) {
        html += `<article class="card-missing">missing<br>${p}<br>seed ${seed}</article>`;
        continue;
      }
      const rawViews = normalViews(r.normal_raw);
      const simViews = normalViews(r.normal_simplified);
      const activePath = activeMeshPath(r);
      const activeUrl = fileUrl(activePath);
      const simplePath = simplifiedMeshPath(r);
      const simpleUrl = fileUrl(simplePath);
      const rawFaces = r.raw_stats ? Number(r.raw_stats.faces).toLocaleString() : "?";
      const simFaces = r.simplified_stats ? Number(r.simplified_stats.faces).toLocaleString() : "?";
      const resolutionLabel = scoreResolution(r, p);
      const eff = r.effective_resolution ? `effective ${r.effective_resolution}` : "";
      const cardId = `card-${selectedImageIndex}-${cardSerial++}`;
      const viewsForButtons = rawViews.length ? rawViews : simViews;
      const scoreHtml = buildScorePanel(imageRecord, seed, p, resolutionLabel);
      const viewButtons = viewsForButtons.map((v, idx) => {
        const viewIdx = v.view_idx ?? idx;
        const rv = rawViews.find(x => Number(x.view_idx) === Number(viewIdx)) || rawViews[idx] || {};
        const sv = simViews.find(x => Number(x.view_idx) === Number(viewIdx)) || simViews[idx] || {};
        const rawImgUrl = fileUrl(rv.path || v.path);
        const simImgUrl = fileUrl(sv.path || v.path);
        // Thumbnails and zoom are driven by raw normal only. simplified normal is kept only for dblclick comparison.
        const thumbUrl = rawImgUrl || simImgUrl;
        const yaw = v.yaw_deg !== undefined ? `${Number(v.yaw_deg).toFixed(1)}°` : `v${idx}`;
        return `<button class="view-button" title="移动鼠标框选 raw normal 高分辨率细节；双击时才加载当前 view 的 simplified normal 对比" data-card-id="${cardId}" data-seed="${seed}" data-pipeline="${p}" data-view-idx="${viewIdx}" data-title="seed ${seed} · ${p} · view ${viewIdx}" data-raw="${rawImgUrl}" data-simple="${simImgUrl}" data-raw-label="raw mesh normal · ${rawFaces} faces" data-simple-label="simplified mesh normal · ${simFaces} faces">
          <span class="thumb-frame">
            <img class="thumb-img" data-src="${thumbUrl}" alt="" loading="eager" decoding="async" />
            <span class="thumb-placeholder">raw loading</span>
            <span class="face-badge">${rawFaces}<br/>faces</span>
            <span class="roi-box"></span>
          </span>
          <span class="view-label">v${viewIdx} ${yaw}</span>
        </button>`;
      }).join("");
      const viewButtonsHtml = viewButtons || `<div class="small">normal preview disabled / missing</div>`;
      const meshViewerHtml = activeUrl ? `<div class="viewer-slot" data-card-id="${cardId}" data-seed="${seed}" data-pipeline="${p}">
            <div class="viewer" data-glb="${activeUrl}"><div class="loading">等待进入视野后加载 simplified GLB...</div></div>
          </div>` : `<div class="missing">missing GLB</div>`;
      const imageViewerHtml = `<div class="viewer-slot image-mode" data-card-id="${cardId}" data-seed="${seed}" data-pipeline="${p}">
            <div class="zoom-viewer">
              <canvas class="zoom-canvas"></canvas>
              <div class="zoom-empty">鼠标移到下方 raw normal 缩略图：这里显示原始高分辨率 raw normal 的框选放大；同 seed 下其他精度同步显示同位置。</div>
              <div class="zoom-caption"></div>
            </div>
          </div>`;
      html += `
        <article class="result-card ${multiViewMode ? "image-compare-mode" : "mesh-mode"}">
          <div class="cell-title"><strong>${p}</strong>${eff ? `<span>${eff}</span>` : ""}<span>${multiViewMode ? `raw ${rawFaces} faces` : `simplified ${simFaces} faces`}</span></div>
          ${scoreHtml}
          ${multiViewMode ? imageViewerHtml : meshViewerHtml}
          ${multiViewMode ? "" : `<div class="links">
            ${simpleUrl ? `<a href="${simpleUrl}" target="_blank">下载 GLB</a>` : ""}
            <span class="small">simplified ${simFaces} faces</span>
          </div>`}
          ${multiViewMode ? `<div class="view-panel">
            <div class="view-panel-head"><span>raw normal 多视图缩略图</span><span>下方为本地降采样；上方细节图用原始高分辨率 · ${viewsForButtons.length} views</span></div>
            <div class="view-buttons">${viewButtonsHtml}</div>
          </div>` : ""}
        </article>`;
    }
    html += `</div></section>`;
  }
  html += `</div>`;
  document.getElementById("gridRoot").innerHTML = html;
  renderScoreSummary();
  if (multiViewMode) {
    document.querySelectorAll(".view-button").forEach(btn => {
      btn.addEventListener("pointerenter", e => activateZoomFromButton(btn, e));
      btn.addEventListener("pointermove", e => activateZoomFromButton(btn, e));
      btn.addEventListener("click", e => activateZoomFromButton(btn, e));
      btn.addEventListener("dblclick", () => openCompare(
        btn.dataset.title,
        btn.dataset.raw,
        btn.dataset.simple,
        btn.dataset.rawLabel,
        btn.dataset.simpleLabel,
      ));
    });
  } else {
    const generation = preloadGeneration;
    const status = document.getElementById("preloadStatus");
    if (status) status.textContent = "正在按需导入 Three.js；多视图模式不会加载这些模块。";
    ensureThree().then(() => {
      if (generation !== preloadGeneration || multiViewMode) return;
      document.querySelectorAll(".viewer").forEach(el => createViewer(el, el.dataset.glb));
    }).catch(err => {
      console.error(err);
      if (status && generation === preloadGeneration) status.textContent = "Three.js 导入失败：检查网络/CDN 或浏览器控制台。";
    });
  }
  warmCurrentPageAssets(preloadGeneration);

  const url = new URL(window.location.href);
  url.searchParams.set("image", imageRecord.image_id);
  window.history.replaceState(null, "", url);
}

function ensureViewerObserver() {
  if (viewerObserver || !("IntersectionObserver" in window)) return;
  viewerObserver = new IntersectionObserver(entries => {
    for (const entry of entries) {
      const v = viewers.find(x => x.container === entry.target);
      if (!v) continue;
      v.visible = entry.isIntersecting;
      if (entry.isIntersecting) {
        maybeLoadViewer(v);
        v.dirty = true;
        requestRender();
      }
    }
  }, { root: null, rootMargin: "650px" });
}
function createViewer(container, url) {
  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x07090d);
  const camera = new THREE.PerspectiveCamera(35, 1, 0.01, 100);
  camera.position.set(0, 0.25, 2.4);
  const renderer = new THREE.WebGLRenderer({
    antialias: true,
    alpha: false,
    powerPreference: "high-performance",
  });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 1.5));
  container.appendChild(renderer.domElement);

  const controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = false;
  controls.enablePan = true;
  controls.screenSpacePanning = true;
  controls.rotateSpeed = 0.9;
  controls.zoomSpeed = 0.9;
  controls.panSpeed = 0.8;
  controls.target.set(0, 0, 0);
  controls.update();

  const group = new THREE.Group();
  scene.add(group);

  const viewer = {
    container,
    url,
    scene,
    camera,
    renderer,
    controls,
    group,
    surface: null,
    wire: null,
    loaded: false,
    loading: false,
    dirty: true,
    disposed: false,
    visible: true,
    resizeObserver: null,
    resize() {
      const rect = container.getBoundingClientRect();
      const w = Math.max(1, Math.floor(rect.width));
      const h = Math.max(1, Math.floor(rect.height));
      if (renderer.domElement.width !== w || renderer.domElement.height !== h) {
        renderer.setSize(w, h, false);
        camera.aspect = w / h;
        camera.updateProjectionMatrix();
        if (this.wire && this.wire.material && this.wire.material.resolution) {
          this.wire.material.resolution.set(w, h);
        }
        return true;
      }
      return false;
    },
    setWireframeWidth(widthPx) {
      if (!this.loaded || !this.surface || !this.wire) {
        this.dirty = true;
        requestRender();
        return;
      }
      this.wire.visible = widthPx > 0;
      this.wire.material.linewidth = Math.max(0.01, widthPx || 0.01);
      const rect = container.getBoundingClientRect();
      this.wire.material.resolution.set(Math.max(1, rect.width), Math.max(1, rect.height));
      this.dirty = true;
      requestRender();
    },
    dispose() {
      this.disposed = true;
      if (viewerObserver) viewerObserver.unobserve(container);
      if (this.resizeObserver) this.resizeObserver.disconnect();
      controls.dispose();
      disposeRenderable(this.group);
      renderer.dispose();
      container.innerHTML = "";
    }
  };
  viewers.push(viewer);

  controls.addEventListener("change", () => {
    syncFrom(viewer);
    viewer.dirty = true;
    requestRender();
  });

  if ("ResizeObserver" in window) {
    viewer.resizeObserver = new ResizeObserver(() => {
      viewer.dirty = true;
      requestRender();
    });
    viewer.resizeObserver.observe(container);
  }
  ensureViewerObserver();
  if (viewerObserver) viewerObserver.observe(container);
  else maybeLoadViewer(viewer);
  requestRender();
}
function maybeLoadViewer(viewer) {
  if (viewer.loaded || viewer.loading || viewer.disposed) return;
  viewer.loading = true;
  const loadingEl = viewer.container.querySelector(".loading");
  const setLoading = msg => { if (loadingEl) loadingEl.textContent = msg; };
  setLoading(meshBufferCache.has(viewer.url) ? "命中预取缓存，解析 simplified GLB..." : "下载 simplified GLB... 已接收 0 B");

  fetchMeshBuffer(viewer.url, received => {
    setLoading(`下载 simplified GLB... 已接收 ${formatBytes(received)}`);
  }, "high").then(({ buffer, cached, shared }) => {
    if (viewer.disposed) return null;
    setLoading(cached ? "预取已完成，解析 GLB..." : (shared ? "等待后台预取完成，解析 GLB..." : "下载完成，解析 GLB..."));
    return loadGltfFromBuffer(buffer);
  }).then(gltf => {
    if (!gltf || viewer.disposed) return;
    const sourceMesh = findFirstMesh(gltf.scene);
    if (!sourceMesh || !sourceMesh.geometry) {
      throw new Error("GLB has no mesh geometry");
    }
    const surfaceGeo = prepareSurfaceGeometry(sourceMesh.geometry);
    const surface = new THREE.Mesh(surfaceGeo, makeCameraSpaceNormalMaterial());

    viewer.group.add(surface);
    viewer.surface = surface;
    normalizeObject(viewer.group);

    setLoading("准备黑色网格线框...");
    requestAnimationFrame(() => {
      if (viewer.disposed) return;
      try {
        ensureWireframe(viewer);
        viewer.loaded = true;
        viewer.setWireframeWidth(wireframeLineWidth);
        if (loadingEl) loadingEl.remove();
        viewer.loading = false;
        viewer.dirty = true;
        requestRender();
      } catch (err) {
        console.error(err);
        setLoading("网格线框构建失败：检查浏览器控制台");
        viewer.loading = false;
        viewer.dirty = true;
        requestRender();
      }
    });
  }).catch(err => {
    console.error(err);
    setLoading("GLB 加载失败：检查路径、压缩响应和浏览器控制台");
    viewer.loading = false;
    viewer.dirty = true;
    requestRender();
  });
}
function loadGltfFromBuffer(buffer) {
  return new Promise((resolve, reject) => {
    // GLTFLoader.parse is async and does not produce useful byte progress; the download step above does.
    gltfLoader.parse(buffer.slice(0), "", resolve, reject);
  });
}
function fetchMeshBuffer(url, onProgress=null, priority="auto") {
  if (!url) return Promise.reject(new Error("empty mesh url"));
  if (meshBufferCache.has(url)) {
    return Promise.resolve({ buffer: meshBufferCache.get(url), cached: true, shared: false });
  }
  if (meshBufferPromises.has(url)) {
    return meshBufferPromises.get(url).then(buffer => ({ buffer, cached: false, shared: true }));
  }
  const promise = (async () => {
    const resp = await fetch(url, { method: "GET", cache: "force-cache", priority });
    if (!resp.ok) throw new Error(`failed to fetch ${url}: ${resp.status}`);
    let buffer;
    if (resp.body && resp.body.getReader) {
      const reader = resp.body.getReader();
      const chunks = [];
      let received = 0;
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        chunks.push(value);
        received += value.byteLength;
        if (onProgress) onProgress(received);
      }
      const merged = new Uint8Array(received);
      let offset = 0;
      for (const chunk of chunks) {
        merged.set(chunk, offset);
        offset += chunk.byteLength;
      }
      buffer = merged.buffer;
    } else {
      buffer = await resp.arrayBuffer();
      if (onProgress) onProgress(buffer.byteLength);
    }
    meshBufferCache.set(url, buffer);
    assetState.set(url, "ready");
    return buffer;
  })();
  meshBufferPromises.set(url, promise);
  assetState.set(url, "queued");
  return promise.finally(() => meshBufferPromises.delete(url)).then(buffer => ({ buffer, cached: false, shared: false })).catch(err => {
    assetState.set(url, "failed");
    throw err;
  });
}
function formatBytes(bytes) {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  let value = bytes;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value.toFixed(unit === 0 ? 0 : 1)} ${units[unit]}`;
}
function disposeRenderable(root) {
  root.traverse(obj => {
    if (obj.geometry) obj.geometry.dispose();
    if (obj.material) {
      if (Array.isArray(obj.material)) obj.material.forEach(m => m && m.dispose && m.dispose());
      else if (obj.material.dispose) obj.material.dispose();
    }
  });
}
function ensureWireframe(viewer) {
  if (!viewer.surface || viewer.wire) return;
  // Heavy step: build once from the simplified mesh geometry immediately after GLB load.
  // Later slider changes only touch LineMaterial.linewidth and visible, so dragging is cheap.
  const wireGeo = new THREE.WireframeGeometry(viewer.surface.geometry);
  const lineGeo = new LineSegmentsGeometry().fromWireframeGeometry(wireGeo);
  wireGeo.dispose();

  const rect = viewer.container.getBoundingClientRect();
  const wireMat = new LineMaterial({
    color: 0x000000,
    linewidth: Math.max(0.01, wireframeLineWidth || 0.01),
    transparent: true,
    opacity: 1.0,
    depthTest: true,
    depthWrite: false,
    polygonOffset: true,
    polygonOffsetFactor: -1,
    polygonOffsetUnits: -1,
  });
  wireMat.resolution.set(Math.max(1, rect.width), Math.max(1, rect.height));

  viewer.wire = new LineSegments2(lineGeo, wireMat);
  viewer.wire.visible = wireframeLineWidth > 0;
  viewer.wire.computeLineDistances();
  viewer.group.add(viewer.wire);
}
function scheduleWireframeWidthUpdate() {
  if (wireframeUpdateRequested) return;
  wireframeUpdateRequested = true;
  requestAnimationFrame(() => {
    wireframeUpdateRequested = false;
    for (const v of viewers) v.setWireframeWidth(wireframeLineWidth);
  });
}
function findFirstMesh(root) {
  let found = null;
  root.traverse(obj => {
    if (!found && obj.isMesh && obj.geometry) found = obj;
  });
  return found;
}
function prepareSurfaceGeometry(inputGeo) {
  const geo = inputGeo.clone();
  if (geo.attributes.color) geo.deleteAttribute("color");
  if (!geo.attributes.normal) geo.computeVertexNormals();
  return geo;
}
function makeCameraSpaceNormalMaterial() {
  return new THREE.ShaderMaterial({
    side: THREE.DoubleSide,
    polygonOffset: true,
    polygonOffsetFactor: 1,
    polygonOffsetUnits: 1,
    vertexShader: `
      varying vec3 vNormalView;
      void main() {
        vNormalView = normalize(normalMatrix * normal);
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
    fragmentShader: `
      varying vec3 vNormalView;
      void main() {
        vec3 n = normalize(vNormalView);
        if (!gl_FrontFacing) n = -n;
        gl_FragColor = vec4(n * 0.5 + 0.5, 1.0);
      }
    `,
  });
}
function normalizeObject(object) {
  const box = new THREE.Box3().setFromObject(object);
  const size = new THREE.Vector3();
  const center = new THREE.Vector3();
  box.getSize(size);
  box.getCenter(center);
  const scale = 1.55 / Math.max(size.x, size.y, size.z, 1e-6);
  object.position.sub(center);
  object.scale.setScalar(scale);
}
function syncFrom(source) {
  if (suppressSync) return;
  suppressSync = true;
  for (const v of viewers) {
    if (v === source || v.disposed) continue;
    v.camera.position.copy(source.camera.position);
    v.camera.quaternion.copy(source.camera.quaternion);
    v.camera.zoom = source.camera.zoom;
    v.camera.fov = source.camera.fov;
    v.camera.updateProjectionMatrix();
    v.controls.target.copy(source.controls.target);
    v.dirty = true;
  }
  source.dirty = true;
  suppressSync = false;
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}
function getPointerImagePosition(btn, event) {
  const frame = btn.querySelector(".thumb-frame") || btn;
  if (!frame || !event) return { x: zoomState.centerX || 0.5, y: zoomState.centerY || 0.5 };
  const rect = frame.getBoundingClientRect();
  if (rect.width <= 0 || rect.height <= 0) return { x: 0.5, y: 0.5 };
  return {
    x: clamp((event.clientX - rect.left) / rect.width, 0, 1),
    y: clamp((event.clientY - rect.top) / rect.height, 0, 1),
  };
}
function activateZoomFromButton(btn, event) {
  if (!multiViewMode) return;
  const url = btn.dataset.raw || btn.dataset.simple;
  if (!url) return;
  const pos = getPointerImagePosition(btn, event);
  zoomState = {
    active: true,
    seed: btn.dataset.seed,
    viewIdx: btn.dataset.viewIdx,
    centerX: pos.x,
    centerY: pos.y,
    sourceTitle: btn.dataset.title || "raw normal detail",
  };
  scheduleZoomUpdate();
}
function scheduleZoomUpdate() {
  if (zoomUpdateRequested) return;
  zoomUpdateRequested = true;
  requestAnimationFrame(() => {
    zoomUpdateRequested = false;
    applyZoomState();
  });
}
function exitZoomMode() {
  zoomState.active = false;
  document.querySelectorAll(".viewer-slot.image-mode").forEach(slot => clearZoomSlot(slot, !multiViewMode));
  document.querySelectorAll(".view-button.roi-active").forEach(btn => btn.classList.remove("roi-active"));
  updateModeToggleButton();
  markAllDirty();
}
function updateModeToggleButton() {
  const btn = document.getElementById("toggleViewButtons");
  if (!btn) return;
  btn.classList.toggle("active", multiViewMode);
  btn.textContent = multiViewMode ? "多视角图：开" : "多视角图：关";
}
function findMatchingViewButton(seed, pipeline, viewIdx) {
  const buttons = document.querySelectorAll(".view-button");
  for (const btn of buttons) {
    if (btn.dataset.seed === String(seed) && btn.dataset.pipeline === String(pipeline) && btn.dataset.viewIdx === String(viewIdx)) {
      return btn;
    }
  }
  return null;
}
function applyZoomState() {
  updateModeToggleButton();
  updateRoiBoxes();
  if (!multiViewMode) return;
  const slots = document.querySelectorAll(".viewer-slot");
  for (const slot of slots) {
    if (!zoomState.active || slot.dataset.seed !== String(zoomState.seed)) {
      clearZoomSlot(slot);
      continue;
    }
    const match = findMatchingViewButton(slot.dataset.seed, slot.dataset.pipeline, zoomState.viewIdx);
    const url = match ? (match.dataset.raw || match.dataset.simple) : "";
    const modeLabel = match && match.dataset.raw ? "raw normal" : "simplified normal fallback";
    const caption = match
      ? `${modeLabel} · ${match.dataset.title || ""} · center (${Math.round(zoomState.centerX * 100)}%, ${Math.round(zoomState.centerY * 100)}%) · range ${Math.round(zoomWindowFraction * 100)}%`
      : `当前 pipeline 缺少 view ${zoomState.viewIdx}`;
    renderZoomSlot(slot, url, caption);
  }
}
function updateRoiBoxes() {
  const sizePct = zoomWindowFraction * 100;
  const leftPct = clamp(zoomState.centerX * 100 - sizePct / 2, 0, 100 - sizePct);
  const topPct = clamp(zoomState.centerY * 100 - sizePct / 2, 0, 100 - sizePct);
  document.querySelectorAll(".view-button").forEach(btn => {
    const active = zoomState.active && btn.dataset.seed === String(zoomState.seed) && btn.dataset.viewIdx === String(zoomState.viewIdx);
    btn.classList.toggle("roi-active", active);
    const roi = btn.querySelector(".roi-box");
    if (!roi) return;
    if (!active) {
      roi.style.display = "";
      return;
    }
    roi.style.left = `${leftPct}%`;
    roi.style.top = `${topPct}%`;
    roi.style.width = `${sizePct}%`;
    roi.style.height = `${sizePct}%`;
  });
}
function clearZoomSlot(slot, leaveImageMode = multiViewMode) {
  if (leaveImageMode) slot.classList.add("image-mode");
  else slot.classList.remove("image-mode");
  const zoom = slot.querySelector(".zoom-viewer");
  if (zoom) zoom.classList.remove("has-image");
  const caption = slot.querySelector(".zoom-caption");
  if (caption) caption.textContent = "";
  const empty = slot.querySelector(".zoom-empty");
  if (empty) empty.textContent = "鼠标移到下方 raw normal 缩略图：这里显示原始高分辨率 raw normal 的框选放大；同 seed 下其他精度同步显示同位置。";
}
function loadPreviewImage(url) {
  if (!url) return Promise.reject(new Error("empty image url"));
  if (previewImageCache.has(url)) return previewImageCache.get(url);
  const promise = new Promise((resolve, reject) => {
    const img = new Image();
    img.decoding = "async";
    img.onload = async () => {
      try {
        if (img.decode) await img.decode();
      } catch (err) {
        // Some browsers reject decode() after onload for cached images; the image is still usable.
      }
      assetState.set(url, "ready");
      resolve(img);
    };
    img.onerror = () => {
      assetState.set(url, "failed");
      reject(new Error(`failed to load ${url}`));
    };
    assetState.set(url, "queued");
    imageCacheUrls.add(url);
    img.src = url;
  });
  previewImageCache.set(url, promise);
  return promise;
}
function fitContainSize(srcW, srcH, maxSize) {
  const scale = Math.min(maxSize / Math.max(srcW, srcH, 1), 1);
  return {
    w: Math.max(1, Math.round(srcW * scale)),
    h: Math.max(1, Math.round(srcH * scale)),
  };
}
function makeThumbnailObjectUrl(url, decodedImg) {
  if (!url || !decodedImg) return Promise.reject(new Error("missing thumbnail source"));
  if (thumbnailUrlCache.has(url)) return Promise.resolve(thumbnailUrlCache.get(url));
  if (thumbnailPromiseCache.has(url)) return thumbnailPromiseCache.get(url);
  const promise = new Promise(resolve => {
    const srcW = decodedImg.naturalWidth || decodedImg.width || THUMB_MAX_SIZE;
    const srcH = decodedImg.naturalHeight || decodedImg.height || THUMB_MAX_SIZE;
    const size = fitContainSize(srcW, srcH, THUMB_MAX_SIZE);
    const canvas = document.createElement("canvas");
    canvas.width = size.w;
    canvas.height = size.h;
    const ctx = canvas.getContext("2d", { alpha: false });
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = "medium";
    ctx.drawImage(decodedImg, 0, 0, size.w, size.h);
    const finish = blob => {
      let objectUrl;
      if (blob) {
        objectUrl = URL.createObjectURL(blob);
      } else {
        objectUrl = canvas.toDataURL("image/jpeg", 0.72);
      }
      thumbnailUrlCache.set(url, objectUrl);
      thumbnailPromiseCache.delete(url);
      resolve(objectUrl);
    };
    if (canvas.toBlob) canvas.toBlob(finish, "image/jpeg", 0.72);
    else finish(null);
  });
  thumbnailPromiseCache.set(url, promise);
  return promise;
}
function revokeThumbnailObjectUrls() {
  for (const objectUrl of thumbnailUrlCache.values()) {
    if (typeof objectUrl === "string" && objectUrl.startsWith("blob:")) {
      URL.revokeObjectURL(objectUrl);
    }
  }
  thumbnailUrlCache.clear();
  thumbnailPromiseCache.clear();
}
function clearDecodedImageCaches() {
  revokeThumbnailObjectUrls();
  previewImageCache.clear();
  for (const url of imageCacheUrls) assetState.delete(url);
  imageCacheUrls.clear();
}
async function revealDomImages(url, decodedImg=null) {
  if (!url) return;
  if (decodedImg && !previewImageCache.has(url)) {
    previewImageCache.set(url, Promise.resolve(decodedImg));
  }
  const thumbUrl = decodedImg ? await makeThumbnailObjectUrl(url, decodedImg) : url;
  document.querySelectorAll("img.thumb-img").forEach(img => {
    if (img.dataset.src !== url || img.dataset.ready === "1") return;
    img.src = thumbUrl;
    img.dataset.ready = "1";
    img.classList.add("ready");
    const frame = img.closest(".thumb-frame");
    if (frame) frame.classList.add("ready");
  });
}

function renderZoomSlot(slot, url, captionText) {
  slot.classList.add("image-mode");
  const zoom = slot.querySelector(".zoom-viewer");
  const canvas = slot.querySelector(".zoom-canvas");
  const empty = slot.querySelector(".zoom-empty");
  const caption = slot.querySelector(".zoom-caption");
  if (caption) caption.textContent = captionText || "";
  if (!zoom || !canvas || !url) {
    if (zoom) zoom.classList.remove("has-image");
    if (empty) empty.textContent = "当前精度缺少该视角的 normal 图。";
    return;
  }
  if (empty) empty.textContent = previewImageCache.has(url) ? "drawing cached normal crop..." : "loading/decode normal crop...";
  const token = String(++zoomDrawToken);
  slot.dataset.zoomToken = token;
  loadPreviewImage(url).then(img => {
    if (slot.dataset.zoomToken !== token || !zoomState.active || !multiViewMode) return;
    zoom.classList.add("has-image");
    drawZoomCanvas(canvas, img, zoomState.centerX, zoomState.centerY, zoomWindowFraction);
  }).catch(err => {
    console.error(err);
    if (slot.dataset.zoomToken !== token) return;
    zoom.classList.remove("has-image");
    if (empty) empty.textContent = "normal 图加载失败。";
  });
}
function drawZoomCanvas(canvas, img, centerX, centerY, windowFraction) {
  const rect = canvas.getBoundingClientRect();
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const cssW = Math.max(1, Math.floor(rect.width));
  const cssH = Math.max(1, Math.floor(rect.height));
  const pixelW = Math.max(1, Math.floor(cssW * dpr));
  const pixelH = Math.max(1, Math.floor(cssH * dpr));
  if (canvas.width !== pixelW || canvas.height !== pixelH) {
    canvas.width = pixelW;
    canvas.height = pixelH;
  }
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = true;
  ctx.imageSmoothingQuality = "high";
  ctx.clearRect(0, 0, pixelW, pixelH);

  const imgW = img.naturalWidth || img.width;
  const imgH = img.naturalHeight || img.height;
  const aspect = pixelW / pixelH;
  const baseCrop = Math.max(4, Math.min(imgW, imgH) * clamp(windowFraction, 0.02, 1.0));
  let cropW = aspect >= 1 ? baseCrop * aspect : baseCrop;
  let cropH = aspect >= 1 ? baseCrop : baseCrop / aspect;
  if (cropW > imgW) {
    const scale = imgW / cropW;
    cropW *= scale;
    cropH *= scale;
  }
  if (cropH > imgH) {
    const scale = imgH / cropH;
    cropW *= scale;
    cropH *= scale;
  }
  const cx = clamp(centerX, 0, 1) * imgW;
  const cy = clamp(centerY, 0, 1) * imgH;
  const sx = clamp(cx - cropW / 2, 0, Math.max(0, imgW - cropW));
  const sy = clamp(cy - cropH / 2, 0, Math.max(0, imgH - cropH));
  ctx.drawImage(img, sx, sy, cropW, cropH, 0, 0, pixelW, pixelH);
}
function resetCamera() {
  suppressSync = true;
  for (const v of viewers) {
    v.camera.position.set(0, 0.25, 2.4);
    v.camera.quaternion.identity();
    v.camera.zoom = 1;
    v.camera.fov = 35;
    v.camera.updateProjectionMatrix();
    v.controls.target.set(0, 0, 0);
    v.controls.update();
    v.dirty = true;
  }
  suppressSync = false;
  requestRender();
}
function collectAssetsForImage(index, mode="mesh", pageDistance=0) {
  const img = MANIFEST.images[index];
  if (!img) return [];
  const urls = [];
  const base = pageDistance * 100;
  // In image mode, do not count or prefetch input/simplified normals. The input image loads separately
  // in the header, and simplified normal is loaded only when the user double-clicks one view.
  if (mode !== "image" && img.input_image) {
    urls.push({ url: fileUrl(img.input_image), type: "image", priority: base + 0, label: "input" });
  }
  for (const r of img.results || []) {
    if (mode === "mesh" && PREFETCH_MESHES) {
      const simple = simplifiedMeshPath(r);
      if (simple) urls.push({ url: fileUrl(simple), type: "mesh", priority: base + 1, label: `mesh ${r.pipeline_type}` });
    }
    for (const v of normalViews(r.normal_raw)) {
      if (v.path) urls.push({ url: fileUrl(v.path), type: "image", priority: base + 1, label: `raw normal ${r.pipeline_type}` });
    }
    // Intentionally skip normal_simplified in image mode. It is fetched only by openCompare() on dblclick.
    if (mode !== "image") {
      for (const v of normalViews(r.normal_simplified)) {
        if (v.path) urls.push({ url: fileUrl(v.path), type: "image", priority: base + 30, label: `simplified normal ${r.pipeline_type}` });
      }
    }
  }
  const seen = new Set();
  return urls
    .filter(x => x.url && !seen.has(x.url) && seen.add(x.url))
    .sort((a, b) => a.priority - b.priority || a.type.localeCompare(b.type));
}
function idle(fn) {
  if ("requestIdleCallback" in window) requestIdleCallback(fn, { timeout: 700 });
  else setTimeout(fn, 40);
}
async function prefetchAsset(item) {
  if (!item || !item.url) return;
  if (item.type === "image") {
    return await loadPreviewImage(item.url);
  }
  return await fetchMeshBuffer(item.url, null, "low");
}
async function prefetchQueue(items, generation, label="后台预取") {
  const status = document.getElementById("preloadStatus");
  const dedup = [];
  const seen = new Set();
  for (const item of items) {
    if (!item.url || seen.has(item.url)) continue;
    seen.add(item.url);
    if (assetState.get(item.url) === "ready") {
      if (item.type === "image") {
        loadPreviewImage(item.url).then(img => revealDomImages(item.url, img)).catch(() => {});
      }
      continue;
    }
    dedup.push(item);
  }
  if (!dedup.length) {
    if (status && generation === preloadGeneration) status.textContent = `${label}：已命中缓存，无需继续下载。`;
    return;
  }
  let done = 0;
  let active = 0;
  let activeMeshes = 0;
  let cursor = 0;
  const maxConcurrent = multiViewMode ? 6 : 3;
  const maxMeshConcurrent = 1;
  const failed = [];
  return new Promise(resolve => {
    const pump = () => {
      if (generation !== preloadGeneration) return resolve();
      while (cursor < dedup.length && active < maxConcurrent) {
        const item = dedup[cursor];
        if (item.type === "mesh" && activeMeshes >= maxMeshConcurrent) break;
        cursor += 1;
        active += 1;
        if (item.type === "mesh") activeMeshes += 1;
        if (status) status.textContent = `${label}：${done}/${dedup.length} 完成，正在 ${item.label || item.type}`;
        prefetchAsset(item).then(async decoded => {
          if (item.type === "image") await revealDomImages(item.url, decoded);
        }).catch(err => {
          console.warn("current-page asset load failed", item.url, err);
          failed.push(item.url);
        }).finally(() => {
          done += 1;
          active -= 1;
          if (item.type === "mesh") activeMeshes -= 1;
          if (status && generation === preloadGeneration) {
            const failText = failed.length ? `，失败 ${failed.length}` : "";
            status.textContent = `${label}：${done}/${dedup.length} 完成${failText}`;
          }
          pump();
        });
      }
      if (cursor >= dedup.length && active === 0) {
        if (status && generation === preloadGeneration) {
          const failText = failed.length ? `，失败 ${failed.length}` : "";
          status.textContent = `${label}完成：${done}/${dedup.length}${failText}。`;
        }
        resolve();
      }
    };
    pump();
  });
}
function warmCurrentPageAssets(generation) {
  const status = document.getElementById("preloadStatus");
  const mode = multiViewMode ? "image" : "mesh";

  // Cross-page preloading is intentionally disabled. The goal is to avoid making page open
  // compete with hidden next-page downloads. Only the selected page is warmed.
  if (!multiViewMode) {
    if (status) status.textContent = "Mesh 模式只按当前可见 viewer 加载 simplified GLB；跨页面预加载已关闭。";
    return;
  }

  const items = collectAssetsForImage(selectedImageIndex, mode, 0)
    .filter(item => item.type === "image");

  // Only raw normal high-res images are transferred here. For the thumbnail grid we generate
  // local low-res object URLs from those decoded images; zoom crop still uses the high-res cache.
  prefetchQueue(items, generation, "当前页 raw normal 加载").then(() => {
    if (generation !== preloadGeneration || !multiViewMode) return;
    const status = document.getElementById("preloadStatus");
    if (status) status.textContent = `当前页 raw normal 已完整下载并 decode：${items.length} 张；下方缩略图为本地降采样，双击时才加载当前 view 的 simplified normal。`;
  });
}
function startNeighborPrefetch(generation) {
  // Kept as a no-op for backward compatibility with older code paths.
  // Cross-page preloading is disabled in this version.
  const status = document.getElementById("preloadStatus");
  if (status && generation === preloadGeneration) {
    status.textContent = "跨页面预加载已关闭。";
  }
}
function openSingleImage(title, url) {
  document.getElementById("modalTitle").textContent = title || "图片预览";
  document.getElementById("modalRawLabel").textContent = "原图";
  document.getElementById("modalRaw").src = url;
  document.getElementById("modalSimple").src = "";
  document.getElementById("modalSimpleCard").style.display = "none";
  document.getElementById("modalGrid").classList.add("single");
  document.getElementById("modalBox").classList.add("single");
  showModal();
}
function setModalImageFromUrl(imgEl, url, fallbackUrl="") {
  if (!imgEl) return;
  imgEl.removeAttribute("src");
  const finalUrl = url || fallbackUrl || "";
  if (!finalUrl) return;
  // If this is a raw normal URL that was already decoded during current-page warming, use it first;
  // otherwise assigning src triggers a normal browser request. simplifiedUrl reaches this path only on dblclick.
  if (previewImageCache.has(finalUrl)) {
    previewImageCache.get(finalUrl).then(decoded => {
      imgEl.src = decoded.src || finalUrl;
    }).catch(() => { imgEl.src = finalUrl; });
  } else {
    imgEl.src = finalUrl;
  }
}
function openCompare(title, rawUrl, simpleUrl, rawLabel, simpleLabel) {
  document.getElementById("modalTitle").textContent = title || "法向渲染对比";
  document.getElementById("modalRawLabel").textContent = rawLabel || "raw mesh normal";
  document.getElementById("modalSimpleLabel").textContent = simpleLabel ? `${simpleLabel}（双击后按需加载）` : "simplified mesh normal";
  setModalImageFromUrl(document.getElementById("modalRaw"), rawUrl || simpleUrl || "");
  setModalImageFromUrl(document.getElementById("modalSimple"), simpleUrl || "", rawUrl || "");
  document.getElementById("modalSimpleCard").style.display = simpleUrl ? "block" : "none";
  document.getElementById("modalGrid").classList.toggle("single", !simpleUrl);
  document.getElementById("modalBox").classList.toggle("single", !simpleUrl);
  showModal();
}
function showModal() {
  document.getElementById("imageModal").classList.add("visible");
  document.body.classList.add("modal-open");
}
function closeModal() {
  document.getElementById("imageModal").classList.remove("visible");
  document.body.classList.remove("modal-open");
}

window.addEventListener("DOMContentLoaded", async () => {
  populateImageSelect();
  await loadScores();
  renderPage();
  document.getElementById("imageSelect").addEventListener("change", e => {
    selectedImageIndex = Number(e.target.value);
    renderPage();
  });
  document.getElementById("pipelineSelect").addEventListener("change", e => {
    visiblePipelineFilter = e.target.value || "__all__";
    renderPage();
  });
  document.getElementById("gridRoot").addEventListener("click", e => {
    const btn = e.target.closest(".score-btn");
    if (btn) {
      e.preventDefault();
      saveScoreFromButton(btn);
    }
  });
  document.getElementById("exportScores").addEventListener("click", () => {
    window.location.href = "/api/scores/export";
  });
  const wireWidthRange = document.getElementById("wireWidthRange");
  const wireWidthValue = document.getElementById("wireWidthValue");
  const updateWireWidthLabel = () => {
    wireWidthValue.textContent = wireframeLineWidth > 0 ? `${wireframeLineWidth.toFixed(2)} px` : "关";
  };
  wireWidthRange.addEventListener("input", e => {
    wireframeLineWidth = Number(e.target.value) || 0;
    updateWireWidthLabel();
    scheduleWireframeWidthUpdate();
  });
  updateWireWidthLabel();
  const zoomWindowRange = document.getElementById("zoomWindowRange");
  const zoomWindowValue = document.getElementById("zoomWindowValue");
  const updateZoomWindowLabel = () => {
    zoomWindowValue.textContent = `${Math.round(zoomWindowFraction * 100)}%`;
  };
  zoomWindowRange.addEventListener("input", e => {
    zoomWindowFraction = clamp(Number(e.target.value) / 100, 0.02, 1.0);
    updateZoomWindowLabel();
    if (zoomState.active) scheduleZoomUpdate();
  });
  updateZoomWindowLabel();
  updateModeToggleButton();
  document.getElementById("toggleViewButtons").addEventListener("click", () => {
    multiViewMode = !multiViewMode;
    zoomState.active = false;
    updateModeToggleButton();
    renderPage();
  });
  document.getElementById("resetCamera").addEventListener("click", resetCamera);
  document.getElementById("heightSelect").addEventListener("change", e => {
    document.documentElement.style.setProperty("--viewer-height", e.target.value);
    setTimeout(() => {
      markAllDirty();
      if (zoomState.active) scheduleZoomUpdate();
    }, 0);
  });
  window.addEventListener("resize", () => {
    markAllDirty();
    if (zoomState.active) scheduleZoomUpdate();
  });
  document.getElementById("closeModal").addEventListener("click", closeModal);
  document.getElementById("imageModal").addEventListener("click", e => {
    if (e.target.id === "imageModal") closeModal();
  });
  window.addEventListener("keydown", e => { if (e.key === "Escape") closeModal(); });
});
</script>
</body>
</html>
"""


COMPRESS_EXTS = {".glb", ".gltf", ".json", ".txt", ".ply", ".obj", ".mtl", ".js", ".css", ".html"}
ALREADY_COMPRESSED_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".gz", ".br", ".zip", ".mp4"}
GLB_MIME = "model/gltf-binary"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--result-root", type=Path, default=Path("/home/nvme04/yyyan/Pixal3D/outputs/pixal3d_resolution_grid_geometry"))
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=7861)
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--prefetch-pages", type=int, default=5, help="Disabled by default. Kept only for CLI compatibility; this version does not cross-prefetch pages.")
    parser.add_argument("--prefetch-meshes", action="store_true", default=False, help="Deprecated compatibility flag. Cross-page mesh prefetch is disabled in this version.")
    parser.add_argument("--no-prefetch-meshes", dest="prefetch_meshes", action="store_false")
    parser.add_argument("--gzip-assets", action="store_true", default=True, help="Serve cached gzip-compressed assets when the browser supports it.")
    parser.add_argument("--no-gzip-assets", dest="gzip_assets", action="store_false")
    parser.add_argument("--min-gzip-bytes", type=int, default=64 * 1024)
    parser.add_argument("--score-table", type=Path, default=None, help="CSV path for quality scores. Defaults to <result-root>/quality_scores.csv.")
    return parser.parse_args()


def load_manifest(result_root: Path) -> Dict[str, Any]:
    manifest_path = result_root / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"manifest.json not found: {manifest_path}")
    with manifest_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def content_type_for(path: Path) -> str:
    if path.suffix.lower() == ".glb":
        return GLB_MIME
    guess, _ = mimetypes.guess_type(str(path))
    return guess or "application/octet-stream"


def is_safe_child(root: Path, requested: Path) -> bool:
    try:
        requested.relative_to(root)
        return True
    except ValueError:
        return False


def compressible(path: Path, min_bytes: int) -> bool:
    suffix = path.suffix.lower()
    if suffix in ALREADY_COMPRESSED_EXTS:
        return False
    if suffix not in COMPRESS_EXTS:
        return False
    try:
        return path.stat().st_size >= min_bytes
    except OSError:
        return False


def gzip_cache_path(cache_dir: Path, rel_path: str, source: Path) -> Path:
    st = source.stat()
    key = f"{rel_path}|{st.st_mtime_ns}|{st.st_size}|gzip".encode("utf-8")
    digest = hashlib.sha256(key).hexdigest()
    return cache_dir / f"{digest}.gz"


def ensure_gzip_cache(source: Path, rel_path: str, cache_dir: Path) -> Optional[Path]:
    cache_dir.mkdir(parents=True, exist_ok=True)
    out = gzip_cache_path(cache_dir, rel_path, source)
    if out.exists() and out.stat().st_size > 0:
        return out
    tmp = out.with_suffix(out.suffix + ".tmp")
    try:
        with source.open("rb") as f_in, gzip.open(tmp, "wb", compresslevel=6) as f_out:
            shutil.copyfileobj(f_in, f_out, length=1024 * 1024)
        # If gzip is not smaller, skip it. This avoids wasting bandwidth on PNG/JPEG-like files.
        if tmp.stat().st_size >= source.stat().st_size:
            tmp.unlink(missing_ok=True)
            return None
        os.replace(tmp, out)
        return out
    except Exception:
        tmp.unlink(missing_ok=True)
        return None


def serve_asset(result_root: Path, rel_path: str, gzip_assets: bool, min_gzip_bytes: int) -> Response:
    requested = (result_root / rel_path).resolve()
    if not is_safe_child(result_root, requested):
        abort(403)
    if not requested.exists() or not requested.is_file():
        abort(404)

    content_type = content_type_for(requested)
    headers = {
        "Cache-Control": "public, max-age=604800, immutable",
        "X-Content-Type-Options": "nosniff",
    }

    accept_encoding = request.headers.get("Accept-Encoding", "")
    if gzip_assets and "gzip" in accept_encoding and compressible(requested, min_gzip_bytes):
        gz = ensure_gzip_cache(requested, rel_path, result_root / ".web_cache" / "gzip")
        if gz is not None:
            response = send_file(gz, mimetype=content_type, conditional=True)
            response.headers["Content-Encoding"] = "gzip"
            response.headers["Vary"] = "Accept-Encoding"
            response.headers.update(headers)
            return response

    response = send_from_directory(result_root, rel_path, mimetype=content_type, conditional=True)
    response.headers.update(headers)
    return response



SCORE_KEYS = ("overall", "local")
DEFAULT_SCORE = "2"
SCORE_FIELDS = [
    "image_id",
    "input_name",
    "seed",
    "pipeline_type",
    "resolution",
    "overall_score",
    "local_score",
    "updated_at",
]


def result_resolution(result: Dict[str, Any]) -> str:
    # Use the pipeline label as the resolution setting, e.g. 512 / 1024 / 1024_cascade / 1536_cascade.
    # Do not prefer effective_resolution here, because it can collapse 1024 and 1024_cascade.
    value = (
        result.get("pipeline_type")
        or result.get("resolution")
        or result.get("effective_resolution")
        or result.get("target_resolution")
        or result.get("mesh_resolution")
        or "unknown"
    )
    return str(value)


def iter_manifest_score_rows(manifest: Dict[str, Any]) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    for image in manifest.get("images", []) or []:
        image_id = str(image.get("image_id") or image.get("input_name") or "")
        input_name = str(image.get("input_name") or "")
        for result in image.get("results", []) or []:
            seed = str(result.get("seed", ""))
            pipeline_type = str(result.get("pipeline_type", ""))
            if not image_id or not seed or not pipeline_type:
                continue
            rows.append({
                "image_id": image_id,
                "input_name": input_name,
                "seed": seed,
                "pipeline_type": pipeline_type,
                "resolution": result_resolution(result),
                "overall_score": DEFAULT_SCORE,
                "local_score": DEFAULT_SCORE,
                "updated_at": "",
            })
    rows.sort(key=lambda r: (r.get("image_id", ""), r.get("seed", ""), r.get("pipeline_type", "")))
    return rows


def normalize_existing_score_row(row: Dict[str, Any]) -> Dict[str, str]:
    """Normalize both the new 2-score CSV and the legacy 4-score CSV.

    Legacy mapping:
      score_1 -> overall_score
      score_2 -> local_score
    Missing or invalid scores default to 2.
    """
    overall = row.get("overall_score") or row.get("overall") or row.get("score_1") or DEFAULT_SCORE
    local = row.get("local_score") or row.get("local") or row.get("score_2") or DEFAULT_SCORE
    out = {
        "image_id": str(row.get("image_id", "") or ""),
        "input_name": str(row.get("input_name", "") or ""),
        "seed": str(row.get("seed", "") or ""),
        "pipeline_type": str(row.get("pipeline_type", "") or ""),
        "resolution": str(row.get("resolution", "") or row.get("pipeline_type", "") or "unknown"),
        "overall_score": DEFAULT_SCORE,
        "local_score": DEFAULT_SCORE,
        "updated_at": str(row.get("updated_at", "") or ""),
    }
    for key, raw in (("overall_score", overall), ("local_score", local)):
        try:
            out[key] = parse_score_value(raw)
        except Exception:
            out[key] = DEFAULT_SCORE
    return out


def ensure_score_table(path: Path, manifest: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing_rows = read_score_rows(path) if path.exists() else []
    existing_by_key = {row_key(row): row for row in existing_rows}

    aligned_rows: List[Dict[str, str]] = []
    for row in iter_manifest_score_rows(manifest):
        existing = existing_by_key.get(row_key(row))
        if existing is not None:
            row["overall_score"] = existing.get("overall_score", DEFAULT_SCORE) or DEFAULT_SCORE
            row["local_score"] = existing.get("local_score", DEFAULT_SCORE) or DEFAULT_SCORE
            row["updated_at"] = existing.get("updated_at", "")
            if existing.get("input_name"):
                row["input_name"] = existing.get("input_name", "")
            if existing.get("resolution") and row.get("resolution") in ("", "unknown"):
                row["resolution"] = existing.get("resolution", "unknown")
        aligned_rows.append(row)
    write_score_rows(path, aligned_rows)


def read_score_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows: List[Dict[str, str]] = []
        for row in reader:
            norm = normalize_existing_score_row(row)
            if norm["image_id"] and norm["seed"] and norm["pipeline_type"]:
                rows.append(norm)
        rows.sort(key=lambda r: (r.get("image_id", ""), r.get("seed", ""), r.get("pipeline_type", "")))
        return rows


def write_score_rows(path: Path, rows: List[Dict[str, str]]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=SCORE_FIELDS)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, DEFAULT_SCORE if field in ("overall_score", "local_score") else "") for field in SCORE_FIELDS})
    os.replace(tmp, path)


def row_key(row: Dict[str, Any]) -> Tuple[str, str, str]:
    return str(row.get("image_id", "")), str(row.get("seed", "")), str(row.get("pipeline_type", ""))


def parse_score_value(value: Any) -> str:
    ivalue = int(value)
    if ivalue not in (1, 2, 3):
        raise ValueError("score_value must be one of 1, 2, 3")
    return str(ivalue)


def summarize_scores(rows: List[Dict[str, str]]) -> Dict[str, Any]:
    by_resolution: Dict[str, Dict[str, Any]] = {}
    for row in rows:
        resolution = row.get("resolution", "") or row.get("pipeline_type", "") or "unknown"
        entry = by_resolution.setdefault(
            resolution,
            {
                "resolution": resolution,
                "count_rows": 0,
                "overall_sum": 0.0,
                "overall_count": 0,
                "local_sum": 0.0,
                "local_count": 0,
                "total_sum": 0.0,
                "total_count": 0,
            },
        )
        entry["count_rows"] += 1
        per_row_values: List[float] = []
        for field, sum_key, count_key in (
            ("overall_score", "overall_sum", "overall_count"),
            ("local_score", "local_sum", "local_count"),
        ):
            try:
                value = float(parse_score_value(row.get(field, DEFAULT_SCORE)))
            except Exception:
                value = float(DEFAULT_SCORE)
            entry[sum_key] += value
            entry[count_key] += 1
            per_row_values.append(value)
        entry["total_sum"] += sum(per_row_values) / len(per_row_values)
        entry["total_count"] += 1

    clean: Dict[str, Dict[str, Any]] = {}
    for resolution, entry in by_resolution.items():
        overall_count = entry["overall_count"]
        local_count = entry["local_count"]
        total_count = entry["total_count"]
        clean[resolution] = {
            "resolution": resolution,
            "count_rows": entry["count_rows"],
            "overall_avg": None if overall_count == 0 else entry["overall_sum"] / overall_count,
            "local_avg": None if local_count == 0 else entry["local_sum"] / local_count,
            "total_avg": None if total_count == 0 else entry["total_sum"] / total_count,
            "overall_count": overall_count,
            "local_count": local_count,
        }
    return {"by_resolution": clean}


def upsert_score(score_table_path: Path, payload: Dict[str, Any]) -> Tuple[Dict[str, str], Dict[str, Any]]:
    image_id = str(payload.get("image_id", "")).strip()
    seed = str(payload.get("seed", "")).strip()
    pipeline_type = str(payload.get("pipeline_type", "")).strip()
    resolution = str(payload.get("resolution", "") or pipeline_type or "unknown")
    if not image_id or not seed or not pipeline_type:
        raise ValueError("image_id, seed, and pipeline_type are required")

    score_key = str(payload.get("score_key", "")).strip()
    if score_key not in SCORE_KEYS:
        # Backward-compatible fallback for the temporary score_index frontend/API.
        score_index = int(payload.get("score_index", 0) or 0)
        if score_index == 1:
            score_key = "overall"
        elif score_index == 2:
            score_key = "local"
        else:
            raise ValueError("score_key must be 'overall' or 'local'")
    score_value = parse_score_value(payload.get("score_value"))

    rows = read_score_rows(score_table_path)
    target_key = (image_id, seed, pipeline_type)
    row = None
    for existing in rows:
        if row_key(existing) == target_key:
            row = existing
            break
    if row is None:
        row = {field: "" for field in SCORE_FIELDS}
        row.update({
            "image_id": image_id,
            "input_name": str(payload.get("input_name", "") or ""),
            "seed": seed,
            "pipeline_type": pipeline_type,
            "resolution": resolution,
            "overall_score": DEFAULT_SCORE,
            "local_score": DEFAULT_SCORE,
        })
        rows.append(row)
    else:
        if payload.get("input_name"):
            row["input_name"] = str(payload.get("input_name") or "")
        row["resolution"] = resolution or row.get("resolution", "unknown")

    row[f"{score_key}_score"] = score_value
    row["updated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    rows.sort(key=lambda r: (r.get("image_id", ""), r.get("seed", ""), r.get("pipeline_type", "")))
    write_score_rows(score_table_path, rows)
    return row, summarize_scores(rows)

def create_app(result_root: Path, prefetch_pages: int, prefetch_meshes: bool, gzip_assets: bool, min_gzip_bytes: int, score_table_path: Path) -> Flask:
    result_root = result_root.resolve()
    manifest = load_manifest(result_root)
    score_table_path = score_table_path.resolve()
    score_lock = threading.Lock()
    ensure_score_table(score_table_path, manifest)
    app = Flask(__name__)

    @app.route("/")
    def index():
        return render_template_string(
            HTML,
            manifest_json=json.dumps(manifest, ensure_ascii=False),
            prefetch_pages_json=json.dumps(max(0, int(prefetch_pages))),
            prefetch_meshes_json=json.dumps(bool(prefetch_meshes)),
            server_compression_json=json.dumps(bool(gzip_assets)),
            score_table_path_json=json.dumps(str(score_table_path)),
        )

    @app.route("/api/manifest")
    def api_manifest():
        return jsonify(manifest)

    @app.route("/api/scores")
    def api_scores():
        with score_lock:
            rows = read_score_rows(score_table_path)
            return jsonify({"rows": rows, "summary": summarize_scores(rows), "score_table": str(score_table_path)})

    @app.route("/api/score", methods=["POST"])
    def api_score():
        payload = request.get_json(force=True, silent=False) or {}
        try:
            with score_lock:
                row, summary = upsert_score(score_table_path, payload)
            return jsonify({"ok": True, "row": row, "summary": summary})
        except Exception as exc:
            return jsonify({"ok": False, "error": str(exc)}), 400

    @app.route("/api/scores/export")
    def api_scores_export():
        with score_lock:
            ensure_score_table(score_table_path, manifest)
        return send_file(score_table_path, mimetype="text/csv", as_attachment=True, download_name=score_table_path.name)

    @app.route("/files/<path:rel_path>")
    def files(rel_path: str):
        return serve_asset(result_root, rel_path, gzip_assets=gzip_assets, min_gzip_bytes=min_gzip_bytes)

    return app


def main() -> None:
    args = parse_args()
    score_table_path = args.score_table or (args.result_root / "quality_scores.csv")
    app = create_app(
        args.result_root,
        prefetch_pages=args.prefetch_pages,
        prefetch_meshes=args.prefetch_meshes,
        gzip_assets=args.gzip_assets,
        min_gzip_bytes=args.min_gzip_bytes,
        score_table_path=score_table_path,
    )
    print(f"Serving result root: {args.result_root.resolve()}")
    print(f"Open: http://{args.host}:{args.port}")
    print(f"gzip assets: {args.gzip_assets}; cross-page prefetch: disabled; default mode: multi-view images")
    print(f"score table: {score_table_path.resolve()}")
    app.run(host=args.host, port=args.port, debug=args.debug)


if __name__ == "__main__":
    main()
